title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 50
        localizable: true
      slug:
        type: text
        width: 25
      theme:
        options:
          default: Default
          reversed: Reversed
          highlight: Highlight
        type: select
        width: 25
        display: Theme
        default: default
      body:
        fieldset: 'partial_body'
        type: partial
        display: Body
taxonomies: true
