title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 50
        localizable: true
      slug:
        type: text
        width: 25
      page_theme:
        width: 25
        display: Theme
        type: color_swatches
        colors:
          dark: '#111'
          light: '#f5f5f5'
      hero_section:
        type: section
        display: Hero
      hero:
        fieldset: partial_hero
        type: partial
        display: Hero
      body:
        fieldset: partial_body
        type: partial
        display: Body
taxonomies: true
