title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 66
        localizable: true
      slug:
        type: text
        width: 33
      body:
        sets:
          wysiwyg:
            display: WYSIWYG
            fields:
              wysiwyg:
                fieldset: 'Partial - Wysiwyg'
                type: partial
                display: WYSIWYG
        type: replicator
        display: Body
taxonomies: true
